name: 'nix-remarkable'
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build
    - name: "Copy ti84-forth"
      run: "mkdir ti84-forth && cp -r result/* ti84-forth && chmod +w -R ti84-forth"
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: ti84-forth
        path: ti84-forth
