name: 'build'
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: cachix/install-nix-action@v15
    - run: nix --experimental-features 'nix-command flakes' build -L
    - name: "Copy ti84-forth"
      run: cp result/forth.8xp .
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v4.3.3
      with:
        name: forth.8xp
        path: forth.8xp
